language: node_js
node_js:
  - 12
cache:
  directories:
  - node_modules
script:
  - npm run deploy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: out
  fqdn: sketchninjas.art
  on:
    branch: master